# Generated by Django 3.0.7 on 2020-09-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
