# Generated by Django 3.0.7 on 2020-08-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0002_auto_20200820_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('workshop_address', models.CharField(blank=True, max_length=400, null=True)),
                ('workshop_phone', models.CharField(default='+919999999999', max_length=13)),
                ('workshop_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='enterprise.Enterprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workshops',
            },
        ),
    ]
