# Generated by Django 3.0.7 on 2020-08-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('settings', '0002_auto_20200803_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name_plural': 'Product types'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name_plural': 'Service types'},
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='enterprise.Enterprise')),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='PaymentModes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode_name', models.CharField(max_length=50)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_mode', to='enterprise.Enterprise')),
            ],
            options={
                'verbose_name_plural': 'Payment modes',
            },
        ),
    ]
