# Generated by Django 3.0.7 on 2020-08-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20200805_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='settings.Priority'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='settings.ProductType'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='settings.ServiceType'),
        ),
    ]
