# Generated by Django 3.0.7 on 2020-08-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_amount',
        ),
    ]
