# Generated by Django 3.0.7 on 2020-08-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
