# Generated by Django 3.0.7 on 2020-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200821_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
