# Generated by Django 3.0.7 on 2020-09-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_user'),
        ('orders', '0011_remove_order_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statushistory', to='workshops.Workshop'),
        ),
    ]
